# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cpf_faker'
gem 'cucumber'
gem 'faker', github: 'stympy/faker'
gem 'httparty'
gem 'parallel_tests', '~> 2.27'
gem 'pry'
gem 'rspec'
gem 'rspec-collection_matchers'
gem 'rubocop-faker'
gem 'rufo'
